---
- name: Install Apache centos docker
  hosts: server
  become: yes
  vars:
    dockerfile: /home/marcones.silva/github/Docker/apache-centos/

  tasks:
  - name: Remove previous images
    command: docker rm -f app
    ignore_errors: yes

  - name: Build images
    command: docker build -t apcentos {{ dockerfile }}

  - name: Create container
    command: docker run -i -d -p 8080:80 --name app -t apcentos
